DELIMITER //

CREATE PROCEDURE SP_INS_FUTBOLISTA(
   IN PV_CEDULA VARCHAR(50),
   IN PV_NOMBRES VARCHAR(50),
   IN PV_APELLIDOS VARCHAR(50),
   IN PD_FECHA_NACIMIENTO DATETIME,
   IN PV_PAIS VARCHAR(50),
   IN PV_DIRECCION VARCHAR(50),
   IN PV_DESCRIPCION VARCHAR(50)
)
BEGIN
   DECLARE CONTADOR_ID INT DEFAULT 0;

   SELECT COUNT(*) INTO CONTADOR_ID
   FROM FUTBOLISTA
   WHERE CEDULA = PV_CEDULA;

   IF CONTADOR_ID = 0 THEN
       INSERT INTO FUTBOLISTA(CEDULA, NOMBRES, APELLIDOS, FECHA_NACIMIENTO, PAIS, DIRECCION, DESCRIPCION)
       VALUES(PV_CEDULA, PV_NOMBRES, PV_APELLIDOS, PD_FECHA_NACIMIENTO, PV_PAIS, PV_DIRECCION, PV_DESCRIPCION);
   END IF;
END //

DELIMITER ;