CREATE TABLE FUTBOLISTA (
    CEDULA VARCHAR(50) NOT NULL PRIMARY KEY,
    NOMBRES VARCHAR(50),
    APELLIDOS VARCHAR(50),
    FECHA_NACIMIENTO DATETIME,
    PAIS VARCHAR(50),
    DIRECCION VARCHAR(50),
    DESCRIPCION VARCHAR(50)
);

CREATE TABLE EQUIPOS (
    ID_EQUIPOS INT NOT NULL PRIMARY KEY,
    NOMBRE_EQUIPO VARCHAR(50),
    DESCRIPCION VARCHAR(50),
    NUMERO_JUGADORES INT,
    PAIS VARCHAR(50),
    FALTAS INT,
    CIUDAD VARCHAR(50),
    ESTADIO VARCHAR(50)
);

CREATE TABLE HISTORICO_EQUIPOS (
    ID_HISTORICO_EQUIPOS INT NOT NULL PRIMARY KEY,
    CEDULA VARCHAR(50),
    ID_EQUIPO INT,
    FECHA_INICIO DATETIME,
    FECHA_FIN DATETIME,
    CONSTRAINT FK_HISTORICO_EQUIPOS_FUTBOLISTA FOREIGN KEY (CEDULA) REFERENCES FUTBOLISTA (CEDULA),
    CONSTRAINT FK_HISTORICO_EQUIPOS_EQUIPOS FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPOS (ID_EQUIPOS)
);