DELIMITER //

CREATE PROCEDURE SP_UPD_FUTBOLISTA(
   IN PV_CEDULA VARCHAR(50),
   IN PV_NOMBRES VARCHAR(50),
   IN PV_APELLIDOS VARCHAR(50),
   IN PV_FECHA_NACIMIENTO DATETIME,
   IN PV_PAIS VARCHAR(50),
   IN PV_DIRECCION VARCHAR(50),
   IN PV_DESCRIPCION VARCHAR(50)
)
BEGIN
   UPDATE FUTBOLISTA
   SET 
       NOMBRES = PV_NOMBRES,
       APELLIDOS = PV_APELLIDOS,
       FECHA_NACIMIENTO = PV_FECHA_NACIMIENTO,
       PAIS = PV_PAIS,
       DIRECCION = PV_DIRECCION,
       DESCRIPCION = PV_DESCRIPCION
   WHERE
       CEDULA = PV_CEDULA;
END //

DELIMITER ;